name: IngeniaMC-Core
version: '${project.version}'
main: me.m64diamondstar.ingeniamccore.Main
api-version: 1.19
authors: [ M64DiamondStar ]
description: The Core plugin of IngeniaMC.
commands:
  wand:
    description: Open the wand selection menu.
  gmc:
    permission: ingenia.admin.gmc
    description: Change gamemode to creative.
  gms:
    permission: ingenia.admin.gms
    description: Change gamemode to creative.
  gma:
    permission: ingenia.admin.gma
    description: Change gamemode to adventure.
  gmsp:
    permission: ingenia.admin.gmsp
    description: Change gamemode to spectator.
  ingenia:
    permission: ingenia.admin
    description: Base command for a LOT of subcommands.
    aliases:
      - ig

