name: IngeniaMC-Core
version: '${project.version}'
main: me.m64diamondstar.ingeniamccore.IngeniaMC
api-version: 1.19
authors: [ M64DiamondStar ]
description: The Core plugin of IngeniaMC.
depend:
  - Train_Carts
  - ProtocolLib
  - FastAsyncWorldEdit
  - OpenAudioMc
  - Animatronics
commands:
  wand:
    description: Open the wand selection menu.
    aliases:
      - wands
  gmc:
    permission: ingenia.admin.gmc
    description: Change gamemode to creative.
  gms:
    permission: ingenia.admin.gms
    description: Change gamemode to creative.
  gma:
    permission: ingenia.admin.gma
    description: Change gamemode to adventure.
  gmsp:
    permission: ingenia.admin.gmsp
    description: Change gamemode to spectator.
  ingenia:
    permission: ingenia.admin
    description: Base command for a LOT of subcommands.
    aliases:
      - ig
  cosmetics:
    description: Open the cosmetic menu.
    aliases:
      - cosmetic
  msg:
    description: Send a private message to someone on the server.
    aliases:
      - tell
  react:
    description: React to the last player that messaged you.
    aliases:
      - r
  admin:
    description: Command for all admin sub-commands.
    permission: ingenia.admin
    aliases:
      - adm
  leave:
    description: Leave the game you're currently playing.
  spawn:
    description: Teleport to the spawn.
  rides:
    description: Open the ride warp menu.
  shops:
    description: Open the shop warp menu.


