name: IngeniaMC-Core
version: '${version}'
main: me.m64diamondstar.ingeniamccore.IngeniaMC
api-version: '1.20'
authors: [ M64DiamondStar ]
description: The Core plugin of IngeniaMC.
depend:
  - Train_Carts
  - TCCoasters
  - FastAsyncWorldEdit
  - Animatronics
  - EffectMaster
  - OpenAudioMc
  - ModelEngine
libraries:
  - net.dv8tion:JDA:5.0.0-beta.23

commands:
  wand:
    description: Open the wand selection menu.
    aliases:
      - wands
  gmc:
    permission: ingenia.admin.gmc
    description: Change gamemode to creative.
  gms:
    permission: ingenia.admin.gms
    description: Change gamemode to creative.
  gma:
    permission: ingenia.admin.gma
    description: Change gamemode to adventure.
  gmsp:
    permission: ingenia.admin.gmsp
    description: Change gamemode to spectator.
  ingenia:
    permission: ingenia.admin
    description: Base command for a LOT of subcommands.
    aliases:
      - ig
  cosmetics:
    description: Open the cosmetic menu.
    aliases:
      - cosmetic
  msg:
    description: Send a private message to someone on the server.
    aliases:
      - tell
  react:
    description: React to the last player that messaged you.
    aliases:
      - r
  admin:
    description: Command for all admin sub-commands.
    permission: ingenia.admin
    aliases:
      - adm
  operate:
    description: Open the operation panel of a ride.
    permission: ingenia.admin
  dispatch:
    description: Dispatch a ride.
    permission: ingenia.admin
  leave:
    description: Leave the game you're currently playing.
  spawn:
    description: Teleport to the spawn.
  rides:
    description: Open the ride warp menu.
  shops:
    description: Open the shop warp menu.
  link:
    description: Link your Minecraft Account to your Discord Account.
  unlink:
    description: Unlink your Minecraft Account from your Discord Account.
  editjoinmessage:
    permission: ingenia.vip
    description: Edit your join message.
  editleavemessage:
    permission: ingenia.vip
    description: Edit your leave message.
  hats:
    description: Open the hat selection menu.
  pants:
    description: Open the pants selection menu.
  shirts:
    description: Open the shirt selection menu.
  shoes:
    description: Open the shoes selection menu.
  backpack:
    description: Manage your backpack.
    aliases:
      - bp
  bodywear:
    description: Manage your bodywear.
  testgui:
    description: Just a test GUI.
    permission: ingenia.admin
  warp:
    description: Teleport to a location.
  feature:
    description: Enable or disable a feature.
    permission: ingenia.admin
    aliases:
      - features
  fixaudio:
    description: Attempt to fix audio issues.
  audiocredits:
    description: Open the credits of audio.
  rules:
    description: Open the rules of the server.
    aliases:
      - tos
      - termsofservice
      - terms
  playtime:
    description: Display your playtime.
    aliases:
      - pt
  npc:
    permission: ingenia.admin
    description: Manage IngeniaMC's npcs.
    aliases:
      - npcs
  settings:
    description: Open the settings menu.
  trash:
    description: Open a virtual trash can.
  website:
    description: Sends you a link to the website.
    aliases:
      - web
  store:
    description: Sends you a link to the store.
    aliases:
      - shop
  discord:
    description: Sends you a link to the discord server.
  youtube:
    description: Sends you a link to the youtube channel.
  tiktok:
    description: Sends you a link to the tiktok channel.
  instagram:
    description: Sends you a link to the instagram channel.
    aliases:
      - insta
  nearestwarp:
    description: Teleport to the nearest warp.
    aliases:
      - stuck

